// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FastGraphFS")>]
[<assembly: AssemblyProductAttribute("FastGraph")>]
[<assembly: AssemblyDescriptionAttribute("Graph datastructures and algorithms.")>]
[<assembly: AssemblyVersionAttribute("3.7.5")>]
[<assembly: AssemblyFileVersionAttribute("3.7.5")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FastGraphFS"
    let [<Literal>] AssemblyProduct = "FastGraph"
    let [<Literal>] AssemblyDescription = "Graph datastructures and algorithms."
    let [<Literal>] AssemblyVersion = "3.7.5"
    let [<Literal>] AssemblyFileVersion = "3.7.5"
