name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, alpha ]

jobs:
  build:

    env:
      BUILD_CONFIGURATION: 'Debug'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: dotnet restore
      run: dotnet restore
    - name: dotnet build
      run: dotnet build --configuration $BUILD_CONFIGURATION --no-restore
    - name: dotnet test
      run: dotnet test --configuration $BUILD_CONFIGURATION --no-restore --no-build --verbosity normal
